Add changed class and component for manage waiter
LoveMyDaughter/TA_EasyRest pull request #43
Opened 2022-07-27 20:05 UTC by taniarezhytska

2022-07-27 20:19 UTC, LoveMyDaughter requested changes
Please make changes.

2022-07-27 20:19 UTC, LoveMyDaughter commented on TAF_EasyRest/TestFramework/PageComponents/CreateNewWaiterPageComponent.cs
> +        private IWebElement _addToSubmitRegistrationWaiterButton => driver.FindElement(By.XPath("//span[contains(text(),'Add')]/parent::button"));
Change name

2022-07-27 20:19 UTC, LoveMyDaughter commented on TAF_EasyRest/TestFramework/PageComponents/CreateNewWaiterPageComponent.cs
> +        private IWebElement _cancelRegistrationWaiterButton => driver.FindElement(By.XPath("//span[contains(text(),'Cancel')]/parent::button"));
Change name

2022-07-27 20:19 UTC, LoveMyDaughter commented on TAF_EasyRest/TestFramework/PageComponents/CreateNewWaiterPageComponent.cs
> +        public CreateNewWaiterPageComponent ClickAddToSubmitRegistrationWaiterButton()
Name...

2022-07-27 20:19 UTC, LoveMyDaughter commented on TAF_EasyRest/TestFramework/PageComponents/CreateNewWaiterPageComponent.cs
> +        public CreateNewWaiterPageComponent ClickCancelRegistrationWaiterButton()
Name...

2022-07-27 20:19 UTC, LoveMyDaughter commented on TAF_EasyRest/TestFramework/PageComponents/PersonalInfoPageComponent.cs
> +    public class ManageWa : BasePage
Name...

2022-07-27 20:19 UTC, LoveMyDaughter commented on TAF_EasyRest/TestFramework/Pages/CurrentOrdersPage.cs
> +        public ManageWa PersonalInfoPageComponent { get; }
Name...

2022-07-27 20:19 UTC, LoveMyDaughter commented on TAF_EasyRest/TestFramework/Pages/ManageWaitersPage.cs
>          private IWebElement _removeWaiterButton(string username) => driver.FindElement(By.XPath($"//span[contains(text(), '{username}')]/parent::div//following-sibling::button"));
Delete this button.

2022-07-27 20:19 UTC, LoveMyDaughter commented on TAF_EasyRest/TestFramework/Pages/OwnerPanelRestaurantsPage.cs
> +        public ManageWa PersonalInfoPageComponent { get; }
Name...

2022-07-28 07:13 UTC, dmatsev commented on TAF_EasyRest/TestFramework/PageComponents/CreateNewWaiterPageComponent.cs
> +        IWebDriver driver { get; }
please specify the access modifier

2022-07-28 08:30 UTC, closed without merging